import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { IntlayerClientProvider } from "next-intlayer";
import { IntlayerServerProvider } from "next-intlayer/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <IntlayerServerProvider locale={locale}>
          <IntlayerClientProvider locale={locale}>
            {children}
          </IntlayerClientProvider>
        </IntlayerServerProvider>
      </body>
    </html>
  );
}